### request meets all criteria

POST http://localhost:8080/ws HTTP/1.1
Content-Type: text/xml;charset=UTF-8

< approved.xml

### request does not meet all criteria

POST http://localhost:8080/ws HTTP/1.1
Content-Type: text/xml;charset=UTF-8

< denied.xml
